#!/bin/bash
# Write a script that parses web servers logs in TSV format as input and displays the 11 hosts or IP addresses which did the most requests.
# The first column of the output must contain the hosts or IP addresses and the second column must contain the number of requests, sorted in descending order.
# Display only the top 11 IP addresses.
# You can use these commands to test your script:
wget -qO- https://bit.ly/2PUrgoc | cut -f 1 | sort | uniq -c | sort -nr | head -n 11

